"""Adicionar data_de_nascimento na tabela usuarios

Revision ID: 73dcc1b6ca11
Revises: 97755fde3d85
Create Date: 2025-05-06 15:43:01.568030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73dcc1b6ca11'
down_revision: Union[str, None] = '97755fde3d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
